from os import environ

SECRET_KEY = environ['SECRET_KEY']
SQLALCHEMY_DATABASE_URI = environ['DATABASE_URL']
SQLALCHEMY_TRACK_MODIFICATIONS = False

AUTH_LOGIN_REDIRECT_URL = 'dashboard.index'
AUTH_LOGOUT_REDIRECT_URL = 'public.index'
AUTH_SESSION_COOKIE_NAME = 'auth_session'
AUTH_STATE_COOKIE_NAME = 'auth_state'
AUTH_CLIENT_ID = environ['AUTH_CLIENT_ID']
AUTH_SECRET_KEY = environ['AUTH_SECRET_KEY']
AUTH_SCOPE = environ['AUTH_SCOPE']
AUTH_CALLBACK_URL = environ['AUTH_CALLBACK_URL']
